---
- name: Configure SELinux
  hosts: all
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Install SETroubleshoot
      yum:
        name: setroubleshoot-server
        state: present

    - name: Set SELinux to permissive
      selinux:
        state: permissive
    
    - name: Disable unconfined user login
      command: setsebool -P unconfined_login off
