---
- name: Installation and configuration HTTPd
  become: yes
  become_method: su
  hosts: apache-servers
  vars:
    http_port: 80
    domain: exam.ext
    name: web
  tasks:
    - name: Install HTTPd
      yum:
        name: httpd
        state: present
    - name: Configure vHost from template
      template:
        dest: /etc/httpd/conf.d/test.conf
        src: templates/vhost.j2
        group: root
        owner: root
        
    - name: Enable HTTPd
      systemd:
        name: httpd
        state: started
        enabled: yes
