---
- name: Install and configure Apache HTTPd
  hosts: webservers
  tasks:
    - name: Install HTTPd
      yum:
        - name: httpd
          state: present
      systemd:
        - name: httpd
          state: started
          enabled: yes
