---
- name: Installation and configuration HTTPd
  hosts: apache-servers
  tasks:
    - name: Install HTTPd
      yum:
        name: httpd
        state: present
    - name: Enable HTTPd
      systemd:
        name: httpd
        state: started
        enabled: yes
